name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install OpenGL
        run: |
          sudo apt-get update
          sudo apt-get -y install libglu1-mesa-dev freeglut3-dev mesa-common-dev

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: "1.6.4"

      - name: Install Shade, run tests, etc
        run: |
          nimble install -dy
          nimble fetch_deps
          nim c -d:debug src/shade.nim
          nimble develop
          tree .usr
          nimble runtests
