name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: "1.6.4"

      - name: Install Shade dependencies
        run: nimble setup

      - name: Build Shade
        run: nimble release

      - name: Run Tests
        run: |
          nimble develop
          nimble runtests
